version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: rails-db
    environment:
      - POSTGRES_DB=rails-dev
      - POSTGRES_PASSWORD=password
    ports:
      - 8201:5432
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
  redis:
    image: redis:latest
    container_name: rails-redis
    ports:
      - 8202:6379
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: rails-web
    ports:
      - 8200:3000
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - SPROCKETS_CACHE=/cache
    volumes:
      - .:/ror
      - cache:/cache
volumes:
  dbdata:
  cache: